apiVersion: v1
kind: Namespace
metadata:
  name: minio-tenant
---
apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
  namespace: minio-tenant
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="minio123"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
    export MINIO_KMS_VAULT_ENDPOINT="http://vault:8200"
    export MINIO_KMS_VAULT_KEY_NAME="minio-key"
    export MINIO_KMS_VAULT_AUTH_TYPE="approle"
    export MINIO_KMS_VAULT_APPROLE_ID="$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace/role-id)"
    export MINIO_KMS_VAULT_SECRET_ID="$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace/secret-id)"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: storage-user
  namespace: minio-tenant
data:
  CONSOLE_ACCESS_KEY: Y29uc29sZQ==
  CONSOLE_SECRET_KEY: Y29uc29sZTEyMw==
type: Opaque
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  labels:
    app: minio
  name: myminio
  namespace: minio-tenant
spec:
  configuration:
    name: storage-configuration
  image: quay.io/minio/minio:RELEASE.2024-08-17T01-24-54Z
  mountPath: /export
  pools:
  - name: pool-0
    servers: 2
    volumeClaimTemplate:
      apiVersion: v1
      kind: PersistentVolumeClaim
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
    volumesPerServer: 2
  requestAutoCert: false
  users:
  - name: storage-user
