apiVersion: v1
kind: Service
metadata:
  name: transform-service
  namespace: minio-tenant
spec:
  selector:
    app: transform-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000