apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  rootuser: bWluaW9hZG1pbg==  # Base64 encoded value for 'minioadmin'
  rootpassword: bWluaW9zZWNyZXQ=  # Base64 encoded value for 'miniosecret'
