apiVersion: v1
kind: Pod
metadata:
  name: minio
  labels:
    app: minio
spec:
  containers:
  - name: minio
    image: minio/minio
    args:
    - server
    - /data
    env:
    - name: MINIO_ROOT_USER
      value: "admin"
    - name: MINIO_ROOT_PASSWORD
      value: "password"
    ports:
    - containerPort: 9000
    - containerPort: 9001