apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-manager-binding
  namespace: minio-rbac
subjects:
- kind: User
  name: minio-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: minio-manager
  apiGroup: rbac.authorization.k8s.io