apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minio-manager
  namespace: minio-rbac
rules:
- apiGroups: ["", "apps", "batch"]
  resources: ["pods", "services", "statefulsets"]
  verbs: ["get", "list", "create", "delete"]