apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minio-cluster-manager
rules:
- apiGroups: ["", "apps"]
  resources: ["statefulsets", "services", "pods"]
  verbs: ["get", "list", "create", "delete"]